import { Inter } from 'next/font/google'
import './globals.scss'
import Link from 'next/link'
import Rodape from '../components/Rodape/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ImunoCheck',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Link href='/'></Link>
        {children}
        <Rodape/>
      </body>
    </html>
  )
}
